# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: de475d7403f9b1b5b2e6b4e3a9462e147cc724b6265c3b3bda238c0f72f297a45977a175aa70bf2e78561f590f70b01b239c83607cd59ec0cebb2d493da985ae

test:
  secret_key_base: dea77d826ff69a5d8eb0b2e072fa2c26bde7e93be8b2d9ec665c93ef96c75cea316cdbcd768e82a2780790b9439d5b4a3c7a2171c0af3abe44c09155bac02e09

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
